// AUTO-GENERATED by scripts/generate-images-js.mjs
// Do not edit by hand; run `node --env-file=.env.local scripts/generate-images-js.mjs`
// Paths are relative to the Supabase bucket and work with your /images/* rewrite or SupabaseImage component.

const images = {
  "about": {
    "teamCollab": "images/about-images/team-collab.png",
    "workSample": "images/about-images/work-sample.png"
  },
  "content": {
    "creativeWorkspaceStages": "images/content-images/creative-workspace-stages.png",
    "dualMonitorSetup": "images/content-images/dual-monitor-setup.png",
    "keyboardCloseup": "images/content-images/keyboard-closeup.png",
    "mobilePreview": "images/content-images/mobile-preview.png",
    "pixelCodeWorkspace": "images/content-images/pixel-code-workspace.png",
    "pixelCodeWorkspace1": "images/content-images/pixel-code-workspace1.png",
    "stepDesignKickoff": "images/content-images/step_design-kickoff.png",
    "stepDevelopmentLaunch": "images/content-images/step_development-launch.png",
    "stepDiscoveryProposal": "images/content-images/step_discovery-proposal.png",
    "websiteConsultation": "images/content-images/website-consultation.png"
  },
  "hero": {
    "homeBg": "images/hero-images/home-bg.jpg",
    "pixelAbout": "images/hero-images/pixel-about.png",
    "pixelContact": "images/hero-images/pixel-contact.png",
    "pixelHome": "images/hero-images/pixel-home.png",
    "pixelHome1": "images/hero-images/pixel-home1.png",
    "pixelServices": "images/hero-images/pixel-services.png"
  },
  "logo": {
    "asset_3_2xZb1bjn": "images/logo-images/Asset_3_2x_zb1bjn.png",
    "asset_4_2xXj1ozf": "images/logo-images/Asset_4_2x_xj1ozf.png",
    "asset_5_2xLlg7lj": "images/logo-images/Asset_5_2x_llg7lj.png",
    "asset_6_2xYqosfx": "images/logo-images/Asset_6_2x_yqosfx.png",
    "clientflowLogo": "images/logo-images/clientflow-logo.png",
    "clientflowWht_2xNpcovv": "images/logo-images/Clientflow-wht_2x_npcovv.png",
    "codeMazeBadgeWhite": "images/logo-images/code-maze-badge-white.png",
    "codeMazeBadge": "images/logo-images/code-maze-badge.png",
    "codeMazeLogoMain": "images/logo-images/code-maze-logo-main.png",
    "codeMazeLogoOnly": "images/logo-images/code-maze-logo-only.png",
    "codeMazeLogoWhite": "images/logo-images/code-maze-logo-white.png"
  },
  "illustrations": {
    "logoDesign": "images/illustrations/logo-design.png",
    "photography": "images/illustrations/photography.png",
    "printMaterials": "images/illustrations/print-materials.png",
    "seo": "images/illustrations/seo.png",
    "videography": "images/illustrations/videography.png",
    "websiteDesign": "images/illustrations/website-design.png"
  }
};

export const aboutImages = images.about;
export const contentImages = images.content;
export const heroImages = images.hero;
export const logoImages = images.logo;
export const illustrations = images.illustrations;

export default images;
